### PR TITLE
Support for guzzle 7

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Review by peter279k — APPROVED** [review]
These changes look good to me, but all commits are very large and messy.

I think it would be great to use Git squashing to convert all commits to one commit.

**Comment by SiroDiaz** [comment]
Thank you @snapshotpl for your work. Changes also seems good to me. I'm going to git squash as @peter279k said.

**Comment by snapshotpl** [comment]
@SiroDiaz thanks. Is it possible to release this change?

**Comment by SiroDiaz** [comment]
yes, I'm going to do it right now. Sorry for the delay, but i was very busy this days.

**Comment by SiroDiaz** [comment]
@snapshotpl version 1.5.0 is now available.

**Pull request merged**
